export interface Movie {
    adult: boolean,
    backdrop_path: string,
    id: number,
    title: string,
    original_title: string,
    overview: string,
    poster_path: string,
    media_type: string,
    original_language: string,
    genre_ids: number[],
    popularity: number,
    releaseDate: Date,
    video: boolean,
    voteAverage: number,
    voteCount: number,
}